### ISSUE TITLE
Installation issues due to Faker

### ISSUE THREAD

**Issue by keyurshah** [CodeSleeve/fixture#6]
Trying to install via Composer, but getting this error

<code>
 Problem 1
    - codesleeve/fixture v1.0.0 requires fzaninotto/faker 1.3.0 -> no matching package found.
</code>

Not sure why as I see faker 1.3 in their repo

**Comment by b3njamin** [comment]
The current version is 1.4 and should be fixed in #11

**Comment by tabennett** [comment]
#11 has been merged.  Closing this one.
